image: "python:3.9.1"

before_script:
  - pip install -r requirements.txt

stages:
  - Analysis
  - Test

mypy:
  stage: Analysis
  script:
  - mypy .

flake8:
  stage: Analysis
  script:
  - flake8 .

black:
  stage: Analysis
  script:
  - black .

unit_test:
  stage: Test
  script:
  - pytest
