image: "python:3.9.1"

stages:
  - Build
  - Analysis
  - Test

build:
  stage: Build
  script:
  - python -m pip install --upgrade pip
  - pip install black flake8 mypy pytest pytest-cov
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

mypy:
  stage: Analysis
  script:
  - mypy --install-types
  - mypy .

flake8:
  stage: Analysis
  script:
  - flake8 .

black:
  stage: Analysis
  script:
  - black --check .

unit_test:
  stage: Test
  script:
  - pytest --cov=deepflow --cov-report term-missing:skip-covered
