image: "python:3.9.1"

before_script:
  - python -m pip install --upgrade pip
  - pip install black flake8 mypy pytest pytest-cov
  - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

stages:
  - Analysis
  - Test

mypy:
  stage: Analysis
  script:
  - mypy .

flake8:
  stage: Analysis
  script:
  - flake8 .

black:
  stage: Analysis
  script:
  - black .

unit_test:
  stage: Test
  script:
  - pytest --cov=deepflow --cov-report term-missing:skip-covered
