#### Black ####
[tool.black]
line-length = 79
exclude = '''
/(
    mod
  | octopytorch
)/
'''


#### Mypy ####
# Global options
[tool.mypy]
exclude = "(octopytorch/|mod/)"
disallow_any_unimported = true
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true 

# Per-module overrides
[[tool.mypy.overrides]]
module = "mod.*"
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = "octopytorch.*"
no_implicit_optional = false

[[tool.mypy.overrides]]
module = [
  "jsonschema.*",
  "matplotlib.*",
  "pandas.*",
  "PIL.*",
  "scipy.*",
  "torchvision.*",
  "tqdm.*",
]
ignore_missing_imports = true


#### PyTest ####
[tool.pytest.ini_options]
testpaths = "tests"
