#### Black ####
[tool.black]
line-length = 79
exclude = "octopytorch"


#### Flake8 ####
[tool.flake8]
exclude = "octopytorch"
extend-ignore = ["E203", "W503"]


#### Mypy ####
# Global options
[tool.mypy]
mypy_path = ".stubs"
exclude = "octopytorch/"
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true 

# Per-module overrides
[[tool.mypy.overrides]]
module = "mod.curation"
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = "octopytorch.*"
no_implicit_optional = false

[[tool.mypy.overrides]]
module = [
  "jsonschema.*",
  "matplotlib.*",
  "pandas.*",
  "PIL.*",
  "torchvision.*",
  "joblib.*",
]
ignore_missing_imports = true


#### PyTest ####
[tool.pytest.ini_options]
testpaths = "tests"
addopts = "--cov=bff --cov=mod --cov-report term-missing:skip-covered"
